### ISSUE TITLE
export? emacs?

### ISSUE THREAD

**Issue by anthrolisp** [3rd/syslang#1]
This looks incredible! I love Hyperlist. Two questions: 
- any plans for export formats?
- do you think it's possible to re-create in emacs?
Thanks!

**Comment by 3rd** [comment]
Hey, yeah, implementing [slang to markdown](https://github.com/3rd/syslang/blob/master/go-syslang/pkg/syslang/document.go#L158) currently! 
Definitely possible to recreate it in Emacs, would probably be easier than in Neovim :cake:
